
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://webservice.walidzaaneun.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertionEuroEnDh", targetNamespace = "http://webservice.walidzaaneun.com/", className = "proxy.ConvertionEuroEnDh")
    @ResponseWrapper(localName = "convertionEuroEnDhResponse", targetNamespace = "http://webservice.walidzaaneun.com/", className = "proxy.ConvertionEuroEnDhResponse")
    @Action(input = "http://webservice.walidzaaneun.com/BanqueService/convertionEuroEnDhRequest", output = "http://webservice.walidzaaneun.com/BanqueService/convertionEuroEnDhResponse")
    public double convertionEuroEnDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://webservice.walidzaaneun.com/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://webservice.walidzaaneun.com/", className = "proxy.GetCompteResponse")
    @Action(input = "http://webservice.walidzaaneun.com/BanqueService/getCompteRequest", output = "http://webservice.walidzaaneun.com/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://webservice.walidzaaneun.com/", className = "proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://webservice.walidzaaneun.com/", className = "proxy.GetComptesResponse")
    @Action(input = "http://webservice.walidzaaneun.com/BanqueService/getComptesRequest", output = "http://webservice.walidzaaneun.com/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

}
